// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

import { StandardButton, VerticalBox, Button, HorizontalBox, Spinner, StyleMetrics, Palette, GridBox, CheckBox, ScrollView } from "std-widgets.slint";
import { Images } from "../components/images.slint";
import { Callbacks} from "../components/callbacks.slint";

export component FirstStart {
    min-width: 700px;
    min-height: 650px;
    VerticalBox {
        spacing: 10px;
        padding: 10px;

        Text {
            text: "First Time Setup";
            font-weight: 800;
            font-size: 20px;
            horizontal-alignment: center;
        }

        Text {
            text: "To optimize your experience with Solus, here are some steps you may do before using your computer.";
            wrap: word-wrap;
            font-size: 14px;
            horizontal-alignment: center;
        }

        ScrollView {
            VerticalBox {
                Rectangle {
                    background: Palette.alternate-background;
                    border-radius: 10px;

                    GridBox {
                        spacing-horizontal: 10px;
                        spacing-vertical: 10px;
                        Text {
                            colspan: 2;
                            row: 0;
                            text: "Update The System";
                            font-weight: 800;
                            font-size: 16px;
                        }

                        Text {
                            col: 0;
                            row: 1;
                            font-size: 14px;
                            wrap: word-wrap;
                            text: "Before installing any application, it is strongly recommended to update your system first.";
                            horizontal-alignment: left;
                        }

                        Button {
                            col: 1;
                            row: 1;
                            height: 48px;
                            width: 200px;
                            text: "Update System";
                            icon: Images.update;
                            colorize-icon: true;
                            clicked => {
                                Callbacks.launchUpdater()
                            }
                        }
                    }
                }

                Rectangle {
                    background: Palette.alternate-background;
                    border-radius: 10px;

                    GridBox {
                        spacing-horizontal: 10px;
                        spacing-vertical: 10px;
                        Text {
                            col: 0;
                            row: 0;
                            text: "Install Additional Driver";
                            font-weight: 800;
                            font-size: 16px;
                        }

                        Text {
                            col: 0;
                            row: 1;
                            font-size: 14px;
                            wrap: word-wrap;
                            text: "If you have Nvidia™ graphic card, you may need to install the propietary driver to get the best experience out of your hardware. If you are not sure, please check out our Help Center.";
                            horizontal-alignment: left;
                        }

                        Button {
                            col: 1;
                            rowspan: 3;
                            text: "Install Driver";
                            height: 48px;
                            width: 200px;
                            icon: Images.driver;
                            colorize-icon: true;
                            clicked => {
                                Callbacks.installDriver()
                            }
                        }
                    }
                }

                Rectangle {
                    background: Palette.alternate-background;
                    border-radius: 10px;

                    GridBox {
                        spacing-horizontal: 10px;
                        spacing-vertical: 10px;
                        Text {
                            col: 0;
                            row: 0;
                            text: "Read the Documentations";
                            font-weight: 800;
                            font-size: 16px;
                        }

                        Text {
                            col: 0;
                            row: 1;
                            font-size: 14px;
                            wrap: word-wrap;
                            text: "Solus Help Center is where you can find articles that will guide you on how to do certain things on Solus.";
                            horizontal-alignment: left;
                        }

                        Button {
                            col: 1;
                            rowspan: 3;
                            text: "Go to Help Center";
                            height: 48px;
                            width: 200px;
                            icon: Images.docs;
                            colorize-icon: true;
                            clicked => {
                                Callbacks.openUrl("https://help.getsol.us");
                            }
                        }
                    }
                }

                Rectangle {
                    background: Palette.alternate-background;
                    border-radius: 10px;

                    GridBox {
                        spacing-horizontal: 10px;
                        spacing-vertical: 10px;

                        Text {
                            colspan: 5;
                            row: 0;
                            text: "Join The Community";
                            font-weight: 800;
                            font-size: 16px;
                        }

                        Text {
                            colspan: 5;
                            row: 1;
                            wrap: word-wrap;
                            font-size: 14px;
                            text: "Still have some questions? Join our forum, we have a good community that is eager to help. You can chat with the staff or other community members on Matrix. Folow us on Mastodon to get bite-sized updates or news about Solus.";
                            horizontal-alignment: left;
                        }

                        Rectangle {
                            col: 0;
                            row: 2;
                        }

                        Button {
                            col: 1;
                            row: 2;
                            height: 48px;
                            width: 200px;
                            text: "Forum";
                            icon: Images.forum;
                            colorize-icon: true;
                            clicked => {
                                Callbacks.openUrl("https://discuss.getsol.us");
                            }
                        }

                        Button {
                            col: 2;
                            row: 2;
                            height: 48px;
                            width: 200px;
                            text: "Matrix";
                            icon: Images.matrix;
                            colorize-icon: true;
                            clicked => {
                                Callbacks.openUrl("https://matrix.to/#/#solus:matrix.org");
                            }
                        }

                        Button {
                            col: 3;
                            row: 2;
                            height: 48px;
                            width: 200px;
                            text: "Mastodon";
                            icon: Images.mastodon;
                            colorize-icon: true;
                            clicked => {
                                Callbacks.openUrl("https://floss.social/@getsolus");
                            }
                        }

                        Rectangle {
                            col: 4;
                            row: 2;
                        }
                    }
                }
            }
        }

        HorizontalBox {
            CheckBox {
                text: "Launch on Startup";
                checked: true;
            }

            StandardButton {
                kind: close;
                height: 48px;
                width: 200px;
            }
        }
    }
}
