// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

import { StandardButton, VerticalBox, Button, HorizontalBox, Spinner, StyleMetrics, Palette, GridBox } from "std-widgets.slint";
import { Images } from "../components/images.slint";
import { Callbacks} from "../components/callbacks.slint";

export component LiveISO {

    VerticalBox {
        spacing: 30px;
        padding-right: 30px;
        padding-left: 30px;
        Text {
            text: "Welcome to Solus";
            font-size: 30pt;
            font-weight: 800;
            wrap: word-wrap;
            horizontal-alignment: center;
        }

        Image {
            horizontal-alignment: center;
            height: 150px;
            source: Images.logo;
        }

        Text {
            text: "A modern Open Source operating system to power your daily needs. Install today, update forever.";
            font-size: 16pt;
            font-weight: 300;
            wrap: word-wrap;
            horizontal-alignment: center;
        }

        HorizontalBox {
            alignment: center;
            spacing: 30px;
            Rectangle {
                background: blue;
                border-color: red;
            }

            GridBox {
                width: 300px;
                spacing-vertical: 25px;
                spacing-horizontal: 15px;
                Image {
                    col: 0;
                    row: 0;
                    source: Images.web;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    vertical-alignment: top;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://getsol.us");
                        }
                    }
                }

                Text {
                    text: "Website";
                    horizontal-alignment: center;
                    col: 0;
                    row: 1;
                }

                Image {
                    col: 1;
                    row: 0;
                    source: Images.github;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://dev.getsol.us");
                        }
                    }
                }

                Text {
                    text: "Github";
                    horizontal-alignment: center;
                    col: 1;
                    row: 1;
                }

                Image {
                    col: 2;
                    row: 0;
                    source: Images.mastodon;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    TouchArea {

                        clicked => {
                            Callbacks.openUrl("https://floss.social/@getsolus");
                        }
                    }
                }

                Text {
                    text: "Mastodon";
                    horizontal-alignment: center;
                    col: 2;
                    row: 1;
                }

                Image {
                    col: 3;
                    row: 0;
                    source: Images.docs;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://help.getsol.us");
                        }
                    }
                }

                Text {
                    text: "Help Guide";
                    horizontal-alignment: center;
                    col: 3;
                    row: 1;
                }
            }

            Rectangle {
                background: blue;
                border-color: red;
            }
        }

        HorizontalBox {
            alignment: center;
            height: 64px;
            spacing: 20px;
            Button {
                text: "Install Solus";
                icon: Images.install;
                colorize-icon: true;
                clicked => {
                    Callbacks.startInstaller();
                }
            }

            Button {
                text: "Continue Live Session";
                icon: Images.play;
                colorize-icon: true;
                clicked => {
                    Callbacks.close();
                }
            }
        }
    }
}
