// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

import { StandardButton, VerticalBox, Button, HorizontalBox, Spinner, StyleMetrics, Palette, GridBox } from "std-widgets.slint";
import { Images } from "../components/images.slint";
import { Callbacks} from "../components/callbacks.slint";

export component LiveISO {
    VerticalBox {
        spacing: 10px;
        padding: 10px;
        Rectangle {
            background: Palette.alternate-background;
            border-radius: 10px;
            padding: 10px;
            VerticalBox {

                Text {
                    text: "Welcome to Solus";
                    font-size: 30pt;
                    font-weight: 800;
                    wrap: word-wrap;
                    horizontal-alignment: center;
                }

                Image {
                    horizontal-alignment: center;
                    height: 150px;
                    source: Images.logo;
                }

                Text {
                    text: "A modern Open Source operating system to power your daily needs. Install today, update forever.";
                    font-size: 16pt;
                    font-weight: 300;
                    wrap: word-wrap;
                    horizontal-alignment: center;
                }
            }
        }

        HorizontalBox {
            alignment: center;
            spacing: 10px;
            padding-top: 20px;
            padding: 10px;
            Rectangle { }

            GridBox {
                width: 400px;
                spacing-vertical: 10px;
                spacing-horizontal: 10px;
                Image {
                    col: 0;
                    row: 0;
                    source: Images.web;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    vertical-alignment: top;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://getsol.us");
                        }
                    }
                }

                Text {
                    text: "Website";
                    horizontal-alignment: center;
                    col: 0;
                    row: 1;
                }

                Image {
                    col: 1;
                    row: 0;
                    source: Images.forum;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    vertical-alignment: top;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://discuss.getsol.us");
                        }
                    }
                }

                Text {
                    text: "Forum";
                    horizontal-alignment: center;
                    col: 1;
                    row: 1;
                }

                Image {
                    col: 2;
                    row: 0;
                    source: Images.docs;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    vertical-alignment: top;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://help.getsol.us");
                        }
                    }
                }

                Text {
                    text: "Help Center";
                    horizontal-alignment: center;
                    col: 2;
                    row: 1;
                }

                Image {
                    col: 3;
                    row: 0;
                    source: Images.github;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://github.com/getsolus/");
                        }
                    }
                }

                Text {
                    text: "Github";
                    horizontal-alignment: center;
                    col: 3;
                    row: 1;
                }

                Image {
                    col: 4;
                    row: 0;
                    source: Images.mastodon;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    TouchArea {

                        clicked => {
                            Callbacks.openUrl("https://floss.social/@getsolus");
                        }
                    }
                }

                Text {
                    text: "Mastodon";
                    horizontal-alignment: center;
                    col: 4;
                    row: 1;
                }

                Image {
                    col: 5;
                    row: 0;
                    source: Images.matrix;
                    colorize: Palette.foreground;
                    height: 32px;
                    preferred-width: 32px;
                    TouchArea {
                        clicked => {
                            Callbacks.openUrl("https://matrix.to/#/#solus:matrix.org");
                        }
                    }
                }

                Text {
                    text: "Matrix";
                    horizontal-alignment: center;
                    col: 5;
                    row: 1;
                }
            }

            Rectangle { }
        }

        HorizontalBox {
            alignment: center;

            spacing: 10px;
            Button {
                text: "Install Solus";
                icon: Images.install;
                height: 64px;
                width: 200px;
                colorize-icon: true;
                clicked => {
                    Callbacks.startInstaller();
                }
            }

            Button {
                text: "Continue Live Session";
                icon: Images.play;
                height: 64px;
                width: 200px;
                colorize-icon: true;
                clicked => {
                    Callbacks.close();
                }
            }
        }
    }
}
