// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

export global Images {
    in property <image> docs: @image-url("../assets/docs.png");
    in property <image> github: @image-url("../assets/github.png");
    in property <image> install: @image-url("../assets/install.png");
    in property <image> logo: @image-url("../assets/logo.svg");
    in property <image> mastodon: @image-url("../assets/mastodon.svg");
    in property <image> play: @image-url("../assets/play.png");
    in property <image> web: @image-url("../assets/web.png");
}
