// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

export global Images {
    in property <image> logo: @image-url("../assets/logo.svg");
    in property <image> mastodon: @image-url("../assets/mastodon.svg");
    in property <image> github: @image-url("../assets/github.png");
    in property <image> matrix: @image-url("../assets/matrix.png");
    in property <image> web: @image-url("../assets/web.png");
    in property <image> forum: @image-url("../assets/forum.png");
    in property <image> docs: @image-url("../assets/docs.png");
    in property <image> install: @image-url("../assets/install.png");
    in property <image> play: @image-url("../assets/continue.png");
    in property <image> driver: @image-url("../assets/driver.png");
    in property <image> update: @image-url("../assets/update.png");
    in property <image> donate: @image-url("../assets/donate.png");
    in property <image> community: @image-url("../assets/people.png");
}
