// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

import { HorizontalBox, VerticalBox } from "std-widgets.slint";
export component SideBar {
    VerticalBox {
        spacing: 0px;
        Rectangle {
            background: red;
        }

        Rectangle {
            background: blue;
        }

        Rectangle {
            background: yellow;
        }
    }
}
