// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

import { StandardButton, VerticalBox, Button, HorizontalBox, Spinner, StyleMetrics, Palette, GridBox } from "std-widgets.slint";
import { Images } from "components/images.slint";
import { LiveISO } from "pages/liveiso.slint";
import { Callbacks } from "components/callbacks.slint";
import { SideBar} from "components/sidebar.slint";
import { FirstStart } from "pages/firststart.slint";
import { Donation } from "pages/donation.slint";

export { Callbacks }

export component MainWindow inherits Window {
    title: root.current_page == 1 ? "Welcome" : "First Setup";
    background: Palette.background;
    icon: Images.logo;

    in property <int> current_page: 1;
    HorizontalBox {
        if root.current_page == 1: LiveISO { }
        if root.current_page == 2: FirstStart { }
        if root.current_page == 3: Donation { }
    }
}
