// SPDX-FileCopyrightText: Copyright © 2025 Muhammad Alfi Syahrin
//
// SPDX-License-Identifier: MPL-2.0

import { StandardButton, VerticalBox, Button, HorizontalBox, Spinner, StyleMetrics, Palette, GridBox } from "std-widgets.slint";
import { Images } from "images.slint";

export component MainWindow inherits Window {
    title: "Welcome";
    background: Palette.background;
    //padding: 20px;
    //no-frame: true;
    icon: Images.logo;
    callback openUrl(string);
    callback close();
    callback startInstaller();
    VerticalBox {
        spacing: 30px;
        padding-right: 30px;
        padding-left: 30px;
        Text {
            text: "Welcome to Solus";
            font-size: 30pt;
            font-weight: 800;
            wrap: word-wrap;
            horizontal-alignment: center;
        }

        Image {
            horizontal-alignment: center;
            height: 150px;
            source: Images.logo;
        }

        Text {
            text: "A modern Open Source operating system to power your daily needs. Install today, update forever.";
            font-size: 16pt;
            font-weight: 300;
            wrap: word-wrap;
            horizontal-alignment: center;
        }

        GridBox {
            padding-top: 30px;
            padding-bottom: 30px;
            spacing-vertical: 30px;
            Rectangle {
                width: 100px;
                col: 0;
                row: 0;
            }

            TouchArea {
                col: 1;
                row: 0;
                Image {
                    source: Images.web;
                    colorize: Palette.foreground;
                    height: 32px;
                    vertical-alignment: top;
                }

                clicked => {
                    root.openUrl("https://getsol.us");
                }
            }

            Text {
                text: "Website";
                horizontal-alignment: center;
                col: 1;
                row: 1;
            }

            TouchArea {
                col: 2;
                row: 0;
                Image {
                    source: Images.github;
                    colorize: Palette.foreground;
                    height: 32px;
                }

                clicked => {
                    root.openUrl("https://dev.getsol.us");
                }
            }

            Text {
                text: "Github";
                horizontal-alignment: center;
                row: 1;
                col: 2;
            }

            TouchArea {
                col: 3;
                row: 0;
                Image {
                    source: Images.mastodon;
                    colorize: Palette.foreground;
                    height: 32px;
                }

                clicked => {
                    root.openUrl("https://floss.social/@getsolus");
                }
            }

            Text {
                text: "Mastodon";
                horizontal-alignment: center;
                row: 1;
                col: 3;
            }

            TouchArea {
                col: 4;
                row: 0;
                Image {
                    source: Images.docs;
                    colorize: Palette.foreground;
                    height: 32px;
                }

                clicked => {
                    root.openUrl("https://help.getsol.us");
                }
            }

            Text {
                text: "Help Guide";
                horizontal-alignment: center;
                row: 1;
                col: 4;
            }

            Rectangle {
                width: 100px;
                col: 5;
                row: 0;
            }
        }

        HorizontalBox {
            alignment: center;
            height: 64px;
            spacing: 20px;
            Button {
                text: "Install Solus";
                icon: Images.install;
                colorize-icon: true;
                clicked => {
                    root.startInstaller();
                }
            }

            Button {
                text: "Continue Live Session";
                icon: Images.play;
                colorize-icon: true;
                clicked => {
                    root.close();
                }
            }
        }
    }
}
